apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
  namespace: default
spec:
  ports:
    - name: "30000"
      port: 30000
      targetPort: 80
  selector:
    io.kompose.service: wordpress
status:
  loadBalancer: {}
